import icon from "../images/Group.svg";
import icon1 from "../images/Group1.svg";
import icon2 from "../images/Group2.svg";
import icon3 from "../images/Group3.svg";
import icon4 from "../images/Group4.svg";
import icons from "../images/iconsn.svg";
import imageTweet from "../images/image.png";
import imageCertifier from "../images/certifier.png";
import iconLikes1 from "../images/GroupL1.svg";
import iconLikes2 from "../images/GroupL2.svg";
import iconLikes3 from "../images/GroupL3.svg";
import iconLikes4 from "../images/GroupL4.svg";
import imageT from "../images/tweet-image.png";
import imageT1 from "../images/image 1.png";
import imageTweeters from "../images/image tweeter.png";
import imageBanners from "../images/arriere-plan-cnn.jpg";
import imageBanners1 from "../images/arriere-plan-new.jpg";
import imageBanners2 from "../images/arriere-plan-twitter.jpg";
import avatarUserCnns from "../images/channels4_profile.jpg";
import avatarUserTnt from "../images/bqp32una36b06hmbulla.png";
import avatarUserTwitte from "../images/twitter.png";
import avatarUserProfi from "../images/arriere-plan-profil.jpg";

export const dataIcons = [icon, icon1, icon2, icon3, icon4];

export const iconsn = icons;
export const imageTweets = imageTweet;
export const iconCertifier = imageCertifier;
export const iconLike1 = iconLikes1;
export const iconLike2 = iconLikes2;
export const iconLike3 = iconLikes3;
export const iconLike4 = iconLikes4;
export const imageTs = imageT;
export const imageTs1 = imageT1;
export const imageTweeter = imageTweeters;
export const imageBanner = imageBanners;
export const imageBanner1 = imageBanners1;
export const imageBanner2 = imageBanners2;
export const avatarUserCnn = avatarUserCnns;
export const avatarUserNew = avatarUserTnt;
export const avatarUserTwitter = avatarUserTwitte;
export const avatarUserProfil = avatarUserProfi;
