import {
  avatarUserCnn,
  avatarUserNew,
  avatarUserProfil,
  avatarUserTwitter,
  iconCertifier,
  imageBanner,
  imageBanner1,
  imageBanner2,
  imageTs1,
  imageTweeter,
  imageTweets,
} from "../assets/Icon";
import profilPhoto from "../images/profile-photo.png";

export const userProfil = [
  {
    userId: 0,
    avatar: profilPhoto,
    userName: "Brandley Ortiz",
    iconCertification: iconCertifier,
    banner: avatarUserProfil,
    lienProfil: "@brandley",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi eos quo aspernatur enim reprehenderit, fugit velit magnam amet cum, molestias doloribus, quaerat adipisci ipsa fuga sunt voluptatem dolorem dolores. Enim.",
    points: "...",
    linkWeb: "brandley.com",
    dateCreated: "A rejoint Twitter en février 2001",
    abonnemets: 4086,
    abonne: 100 + " M",
    suiviPar: "Suivi par Benito et Matthieu Nzing",
    isLogin: true,
  },
  {
    userId: 1,
    avatar: avatarUserCnn,
    userName: "CNN",
    iconCertification: iconCertifier,
    banner: imageBanner,
    lienProfil: "@CNN",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi eos quo aspernatur enim reprehenderit, fugit velit magnam amet cum, molestias doloribus, quaerat adipisci ipsa fuga sunt voluptatem dolorem dolores. Enim.",
    points: "...",
    linkWeb: "cnn.com",
    dateCreated: "A rejoint Twitter en février 2007",
    abonnemets: 1086,
    abonne: 62 + " M",
    suiviPar: "Suivi par Benito et PlayStation",
    isLogin: false,
  },
  {
    userId: 2,
    avatar: avatarUserNew,
    userName: "The New York Times",
    iconCertification: iconCertifier,
    banner: imageBanner1,
    lienProfil: "@nytimes",
    description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
    points: "...",
    linkWeb: "nytimes.com",
    dateCreated: "A rejoint Twitter en février 2012",
    abonnemets: 2086,
    abonne: 72 + " M",
    suiviPar: "Suivi par Matthieu et Ligue des champions",
    isLogin: false,
  },
  {
    userId: 3,
    avatar: avatarUserTwitter,
    userName: "Twitter",
    iconCertification: iconCertifier,
    banner: imageBanner2,
    lienProfil: "@Twitter",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
    points: "...",
    linkWeb: "twitter.com",
    dateCreated: "A rejoint Twitter en février 2005",
    abonnemets: 9850,
    abonne: 995 + " M",
    suiviPar: "Suivi par Sacre et Sylvin",
    isLogin: false,
  },
];
